spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    root: INFO
    com.asohcloak: DEBUG
    org.hibernate.SQL: DEBUG

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true