spring:
  config:
    import: "optional:file:.env[.properties]"

  application:
    name: ${APP_NAME}

  datasource:
    url: jdbc:postgresql://${DATABASE_POSTGRESQL_HOST}:${DATABASE_POSTGRESQL_PORT}/${DATABASE_POSTGRESQL_NAME}
    username: ${DATABASE_POSTGRESQL_USER}
    password: ${DATABASE_POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: false
    locations: classpath:db/migration
    url: jdbc:postgresql://${DATABASE_POSTGRESQL_HOST}:${DATABASE_POSTGRESQL_PORT}/${DATABASE_POSTGRESQL_NAME}
    user: ${DATABASE_POSTGRESQL_USER}
    password: ${DATABASE_POSTGRESQL_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

server:
  port: ${APP_PORT}
  servlet:
    context-path: /api/${API_VERSION}

keycloak:
  admin:
    server-url: ${KEYCLOAK_SERVER_URL}
    realm: ${KEYCLOAK_REALM}
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID}
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}

resend:
  api-key: ${RESEND_API_KEY}
  sender:
    email: ${RESEND_SENDER_EMAIL}
    name: ${RESEND_SENDER_NAME}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
  allowed-methods: ${ALLOWED_METHODS}

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
      enabled: true
    show-actuator: true

minio:
  endpoint: ${MINIO_ENDPOINT}
  port: ${MINIO_PORT}
  console-port: ${MINIO_CONSOLE_PORT}
  username: ${MINIO_USERNAME}
  password: ${MINIO_PASSWORD}
  bucket-name: ${MINIO_BUCKET_NAME}
  use-ssl: ${MINIO_USE_SSL}
  region: ${MINIO_REGION}

